name: hello world
on:
  push:
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY IS $(date +%y-%m-%d)" >> $GITHUB_ENV 
      - run: echo Hello World, today is ${{ env.TODAY }}! 
